[theme]
primaryColor = "#147D73"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F7"
textColor = "#183340"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 10
